apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: monntterro/finance-backend:latest
          ports:
            - name: api
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
