kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-configmap
data:
  # JPA
  JPA_IS_SHOW_SQL: "true"

  # Flyway
  FLYWAY_SCHEMA: "public"

  # CORS
  CORS_ORIGIN_1: "http://frontend.local:8080" # должен совпадать как и CORS в ./services/gateway/configmap.yaml
  CORS_ORIGIN_2: "-"

  # Postgres
  PG_PORT_FOR_CONNECT: "5432"
  PG_HOST_FOR_CONNECT: "backend-postgres-service"